# Generated by Django 4.0.4 on 2022-08-28 09:27

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_algotrade_index_algotrade_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gini_protofilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('df', jsonfield.fields.JSONField()),
            ],
        ),
    ]
