# Generated by Django 4.0.4 on 2022-08-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_gini_protofilo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gini_protofilo',
        ),
    ]
